spring.datasource.url=jdbc:postgresql://ep-icy-surf-act7r2u8-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_TjXvOmdw13Ey&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password="wiXF#L6Hx$"

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true